import test from 'node:test';import assert from 'node:assert/strict';import {loadHistory,saveResult,compatibleHistory,priorHistory,summarize,validResult} from '../dist/src/history.js';
const r={id:'a',gameId:'digitspan',version:1,mode:'timed',difficulty:'standard',timestamp:Date.now(),elapsed:90,attempts:10,correct:8,metrics:{span:5},scored:true};
function memory(value='[]'){return {getItem:()=>value,setItem:(_,v)=>value=v};}
test('corrupt or unavailable storage is recoverable',()=>{assert.deepEqual(loadHistory(memory('{bad')).records,[]);assert.ok(loadHistory(memory('{bad')).warning);assert.ok(loadHistory({getItem(){throw Error('blocked')}}).warning);assert.equal(saveResult({setItem(){throw Error()},getItem:()=>null},r).saved,false);});
test('history validates and roundtrips records',()=>{const s=memory();assert.equal(saveResult(s,r).saved,true);assert.deepEqual(loadHistory(s).records,[r]);assert.equal(validResult({...r,correct:11}),false);assert.equal(validResult({...r,elapsed:-1}),false);assert.equal(validResult({...r,gameId:'<script>'}),false);});
test('comparison excludes incompatible records and current result',()=>{const a=[r,{...r,id:'b',mode:'learn'},{...r,id:'c',difficulty:'hard'},{...r,id:'d',version:2},{...r,id:'e',gameId:'pulse'},{...r,id:'f'}];assert.deepEqual(compatibleHistory(a,r).map(x=>x.id),['f']);});
test('zero baseline is not divided and reflections are not scored',()=>{assert.equal(summarize([{...r,correct:0},r]).improvement,null);assert.equal(summarize([{...r,scored:false}]).accuracy,null);assert.equal(summarize([r]).accuracy,80);});
test('historical result comparisons exclude later sessions even at equal timestamps',()=>{const later={...r,id:'later'},before={...r,id:'before',timestamp:r.timestamp-1};assert.deepEqual(priorHistory([before,r,later],r),[before]);assert.deepEqual(priorHistory([r,later],r),[]);assert.deepEqual(priorHistory([before],r),[before]);});
test('malformed nested reflection responses are rejected',()=>{assert.equal(validResult({...r,gameId:'portrait',scored:false,metrics:{responses:[null]}}),false);assert.equal(validResult({...r,gameId:'portrait',scored:false,metrics:{responses:[{prompt:'Hi',choice:'A',trait:'Planning'}]}}),true);});
test('baseline reports first compatible speed and repeat improvement',()=>{const s=summarize([{...r,elapsed:120,correct:4},{...r,elapsed:120,correct:6}]);assert.equal(s.baseline,2);assert.equal(s.improvement,50);assert.equal(s.repeat,true);});
